name: "Terraform deploy"

on:
  workflow_call:
    inputs:
      azure_tenant:
        description: "Azure tenant"
        required: true
        type: string
      azure_subscription:
        description: "Azure subscription"
        required: true
        type: string
    secrets:
      az_client_id:
        description: "Azure AD Client ID"
        required: true
      az_client_secret:
        description: "Azure AD Client secret"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
       with:
         ref: ${{ inputs.branch }}

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0

     - name: Terraform init
       working-directory: terraform
       id: init
       run: terraform init

     - name: Terraform format
       working-directory: terraform
       id: fmt
       run: terraform fmt -check

     - name: Terraform validate
       working-directory: terraform
       id: validate
       run: terraform validate

     - name: Terraform plan
       working-directory: terraform
       id: plan
       run: terraform plan -no-color -input=false -var-file=dev/terraform.tfvars 
       env:
        ARM_CLIENT_ID: ${{ secrets.az_client_id }} 
        ARM_CLIENT_SECRET: ${{ secrets.az_client_secret }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.azure_subscription }}
        ARM_TENANT_ID: ${{ inputs.azure_tenant }}

     - name: Terraform Apply
       working-directory: terraform
       id: apply
       run: terraform apply -no-color -input=false -var-file=dev/terraform.tfvars 
       env:
        ARM_CLIENT_ID: ${{ secrets.az_client_id }} 
        ARM_CLIENT_SECRET: ${{ secrets.az_client_secret }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.azure_subscription }}
        ARM_TENANT_ID: ${{ inputs.azure_tenant }}
